# Research input and output
 
Data downloaded from http://data.worldbank.org
https://data.worldbank.org/indicator/IP.JRN.ARTC.SC?end=2018&start=2018&view=bar
https://data.worldbank.org/indicator/SP.POP.SCIE.RD.P6
https://data.worldbank.org/indicator/GB.XPD.RSDV.GD.ZS?end=2018&start=2018&view=map&year=2010

### Clean Data

In [1]:
%matplotlib notebook

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [ ]:
pip install openpyxl

In [72]:
# Take in all of our wrestling data and read it into pandas
rd_exp = "data/Research and development expenditure (% of GDP).csv"
rd_pmp = "data/Researchers in R&D (per million people).csv"
rd_journal = "data/scientific and technical journal articles.csv"


rd_exp_df = pd.read_csv(rd_exp,skiprows=4,index_col='Country Name')
rd_pmp_df = pd.read_csv(rd_pmp,skiprows=4,index_col='Country Name')
rd_journal_df = pd.read_csv(rd_journal,skiprows=4,index_col='Country Name')
rd_exp_df.head()

,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,ABW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,AFE,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,AFG,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,AFW,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,AGO,Research and development expenditure (% of GDP),GB.XPD.RSDV.GD.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.03229,NaN,NaN,NaN,NaN,NaN

In [89]:
# drop columns
exp_cleaned=rd_exp_df.dropna(axis=1,how='all').drop(columns=['Country Code','Indicator Code','Indicator Name'])
pmp_cleaned=rd_pmp_df.dropna(axis=1,how='all').drop(columns=['Country Code','Indicator Code','Indicator Name'])
journal_cleaned=rd_journal_df.dropna(axis=1,how='all').drop(columns=['Country Code','Indicator Code','Indicator Name'])
exp_cleaned

,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Eastern and Southern,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Africa Western and Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03229,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
South Africa,NaN,0.58354,NaN,NaN,NaN,0.71578,NaN,0.76051,0.81334,0.86315,...,0.83562,0.73704,0.73451,0.73363,0.72488,0.77115,0.79846,0.81882,0.83215,NaN
Zambia,0.01104,0.00737,NaN,NaN,NaN,NaN,0.00544,0.00847,0.02223,0.02493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
exp_cleaned2=exp_cleaned.dropna(axis=0,how='all')
pmp_cleaned2=pmp_cleaned.dropna(axis=0,how='all')
journal_cleaned2=journal_cleaned.dropna(axis=0,how='all')
exp_cleaned2

,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Country Name,,,,,,,,,,,,,,,,,,,,,
Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03229,NaN,NaN
Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.48622,NaN,NaN,0.69360,0.89504,0.96366,NaN,1.30316
Argentina,0.41749,0.41959,0.41131,0.45337,0.43884,0.42461,0.38886,0.41013,0.40376,0.42074,...,0.58398,0.56104,0.56597,0.63491,0.61849,0.59396,0.62262,0.55815,0.54152,NaN
Armenia,NaN,0.18692,0.22601,0.21400,0.19106,0.27987,0.25255,0.32109,0.25659,0.25761,...,0.29093,0.24139,0.27014,0.23853,0.22216,0.24151,0.25002,0.23305,0.22788,0.18913
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Venezuela, RB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.18907,...,0.24014,0.18823,0.15296,0.25010,0.31853,0.33713,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,0.06603,0.03765,0.03422,0.02929,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,0.19273,NaN,NaN,NaN,...,NaN,NaN,0.19044,NaN,0.37359,NaN,0.44113,NaN,0.52674,NaN
South Africa,NaN,0.58354,NaN,NaN,NaN,0.71578,NaN,0.76051,0.81334,0.86315,...,0.83562,0.73704,0.73451,0.73363,0.72488,0.77115,0.79846,0.81882,0.83215,NaN
Zambia,0.01104,0.00737,NaN,NaN,NaN,NaN,0.00544,0.00847,0.02223,0.02493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
exp_cleaned2.to_excel("exp_cleaned.xlsx")
pmp_cleaned2.to_excel("pmp_cleaned.xlsx")
journal_cleaned2.to_excel("journal_cleaned.xlsx")

In [97]:
# swap rows and columns

exp_t=exp_cleaned2.transpose()
pmp_t=pmp_cleaned2.transpose()
journal_t=journal_cleaned2.transpose()
exp_t

Country Name,Angola,Albania,United Arab Emirates,Argentina,Armenia,American Samoa,Australia,Austria,Azerbaijan,Burundi,...,Ukraine,Uruguay,United States,Uzbekistan,St. Vincent and the Grenadines,"Venezuela, RB",Virgin Islands (U.S.),Vietnam,South Africa,Zambia
1996,NaN,NaN,NaN,0.41749,NaN,NaN,1.66650,1.58077,0.23533,NaN,...,NaN,0.26501,2.45001,NaN,NaN,NaN,NaN,NaN,NaN,0.01104
1997,NaN,NaN,NaN,0.41959,0.18692,NaN,NaN,1.65491,0.36950,NaN,...,1.19230,0.34994,2.47983,NaN,NaN,NaN,NaN,NaN,0.58354,0.00737
1998,NaN,NaN,NaN,0.41131,0.22601,NaN,1.51645,1.73155,0.42125,NaN,...,1.06993,0.19186,2.50401,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999,NaN,NaN,NaN,0.45337,0.21400,NaN,NaN,1.84537,0.39289,NaN,...,0.96968,0.22417,2.54965,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000,NaN,NaN,NaN,0.43884,0.19106,NaN,1.57558,1.88602,0.33600,NaN,...,0.96213,0.20925,2.62879,0.36063,NaN,NaN,NaN,NaN,NaN,NaN
2001,NaN,NaN,NaN,0.42461,0.27987,NaN,NaN,1.99210,0.34001,NaN,...,1.02429,NaN,2.64830,0.34544,0.04306,NaN,NaN,NaN,0.71578,NaN
2002,NaN,NaN,NaN,0.38886,0.25255,NaN,1.75161,2.06598,0.30155,NaN,...,0.99917,0.23818,2.55926,0.29356,0.12028,NaN,0.06603,0.19273,NaN,0.00544
2003,NaN,NaN,NaN,0.41013,0.32109,0.18680,NaN,2.17456,0.32496,NaN,...,1.11287,NaN,2.56455,0.26825,NaN,NaN,0.03765,NaN,0.76051,0.00847
2004,NaN,NaN,NaN,0.40376,0.25659,0.32337,1.85456,2.16612,0.29831,NaN,...,1.08258,NaN,2.50243,0.27041,NaN,NaN,0.03422,NaN,0.81334,0.02223
2005,NaN,NaN,NaN,0.42074,0.25761,0.36473,NaN,2.37324,0.21994,NaN,...,1.03197,NaN,2.51697,0.23741,NaN,0.18907,0.02929,NaN,0.86315,0.02493
2006,NaN,NaN,NaN,0.45216,0.24057,0.39313,2.18552,2.35923,0.17165,NaN,...,0.95000,0.36539,2.55764,0.22395,NaN,0.31742,0.03108,NaN,0.89815,NaN
2007,NaN,0.08757,NaN,0.46007,0.21107,NaN,NaN,2.41843,0.17006,0.20068,...,0.85403,0.42472,2.63161,0.21721,NaN,0.20110,0.02707,NaN,0.88287,NaN
2008,NaN,0.15412,NaN,0.47055,0.22438,NaN,2.40370,2.56945,0.16554,0.15417,...,0.84727,0.37973,2.76791,0.19354,NaN,0.23803,NaN,NaN,0.88816,0.27819
2009,NaN,NaN,NaN,0.58398,0.29093,NaN,NaN,2.59674,0.24976,0.14096,...,0.85727,0.41252,2.81270,0.20315,NaN,0.24014,NaN,NaN,0.83562,NaN
2010,NaN,NaN,NaN,0.56104,0.24139,NaN,2.37586,2.72610,0.21848,0.13719,...,0.83346,0.34115,2.73540,0.19523,NaN,0.18823,NaN,NaN,0.73704,NaN
2011,NaN,NaN,0.48622,0.56597,0.27014,NaN,2.23765,2.66868,0.21084,NaN,...,0.73780,0.34870,2.76525,0.19499,NaN,0.15296,NaN,0.19044,0.73451,NaN
2012,NaN,NaN,NaN,0.63491,0.23853,NaN,NaN,2.91472,0.21427,0.10702,...,0.75167,0.32760,2.68166,0.20210,NaN,0.25010,NaN,NaN,0.73363,NaN
2013,NaN,NaN,NaN,0.61849,0.22216,NaN,2.17870,2.95492,0.20969,NaN,...,0.76175,0.32113,2.70972,0.19662,NaN,0.31853,NaN,0.37359,0.72488,NaN
2014,NaN,NaN,0.69360,0.59396,0.24151,NaN,NaN,3.08429,0.20978,NaN,...,0.65034,0.33579,2.71924,0.16172,NaN,0.33713,NaN,NaN,0.77115,NaN
2015,NaN,NaN,0.89504,0.62262,0.25002,NaN,1.91943,3.04979,0.22232,NaN,...,0.61477,0.36446,2.71742,0.17373,NaN,NaN,NaN,0.44113,0.79846,NaN
2016,0.03229,NaN,0.96366,0.55815,0.23305,NaN,NaN,3.12588,0.20637,NaN,...,0.48339,0.40845,2.76145,0.18156,NaN,NaN,NaN,NaN,0.81882,NaN
2017,NaN,NaN,NaN,0.54152,0.22788,NaN,1.87372,3.05212,0.18468,NaN,...,0.44839,0.48393,2.81741,0.15566,NaN,NaN,NaN,0.52674,0.83215,NaN
2018,NaN,NaN,1.30316,NaN,0.18913,NaN,NaN,3.17177,0.18484,0.21028,...,0.47134,NaN,2.83766,0.12976,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
# save as excel
exp_t.to_excel("exp.xlsx")
pmp_t.to_excel("pmp.xlsx")
journal_t.to_excel("journal.xlsx")

Collecting openpyxl
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.9
Note: you may need to restart the kernel to use updated packages.